# Change these first
owner: quocthinhvo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Cloud Storage
    url: http://kode.ddns.net:8000
    icon: https://avatars.githubusercontent.com/u/35781395?s=200&v=4

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/58879335?s=200&v=4
  name: Cloud Status
  introTitle: "Status of cloud service"
  introMessage: 
  navbar:
    - title: Home
      href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: https://t.me/quocthinhvo

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
